name: final_d100
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - pip=24.2
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - lightgbm
  - statsmodels
  - joblib
  - numexpr
  - jupyter
  - jupyterlab
  - ipykernel
  - ipython
  - ipywidgets
  - jupyterlab_server
  - jupyterlab_widgets
  - jupyter_server
  - jupyter_client
  - notebook
  - nbconvert
  - nbformat
  - pre-commit
  - tqdm
  - fsspec
  - pyarrow
  - fastparquet
  - yaml
  - pyyaml
  - requests
  - virtualenv
  - wheel
  - setuptools
  - pip
  - pyzmq
  - tornado
  - traitlets
  - terminado
  - psutil
  - python-dateutil
  - pytz
  - certifi
  - idna
  - urllib3
  - soupsieve
  - entrypoints
  - markupsafe
  - jinja2
  - prometheus_client
  - send2trash
  - webcolors
  - websocket-client
  - typing-extensions
  - typing_extensions
  - six
  - wrapt
  - rich
  - debugpy
  - threadpoolctl
  - filelock
  - platformdirs
  - zipp
  - zlib
  - xz
  - bzip2
  - openssl
  - ca-certificates
  - tabmat
  - formulaic
  - click
  - pip:
      - alembic
      - category-encoders
      - dython
      - optuna
      - imbalanced-learn
      - shap
      - polars
      - dalex
      - feature-engine
      - glum
      - plotly
      - rich-click
      - sqlalchemy
      - pytest
      - pytest-cov
      - kaleido
      - fitter
